name: secure_web_lock
description: A Flutter package for implementing secure auto-locking for web applications to prevent unauthorized access during periods of inactivity.
version: 0.1.0
homepage: https://github.com/ami231/secure_web_lock
repository: https://github.com/ami231/secure_web_lock

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0
  go_router: ^10.0.0
  universal_html: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/web/secure_web_lock.js

license: MIT